import { pgTable, varchar, text, doublePrecision } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const dntLeishmania = pgTable("dnt_leishmania", {
	articleChemblId: varchar("article_chembl_id", { length: 255 }),
	smiles: text(),
	compoundName: text("compound_name"),
	molecularWeight: doublePrecision("molecular_weight"),
	molecularFormula: text("molecular_formula"),
	alogp: doublePrecision(),
	standardType: text("standard_type"),
	standardRelation: text("standard_relation"),
	standardValue: doublePrecision("standard_value"),
	standardUnits: text("standard_units"),
	comment: text(),
	mutagenicityConsensusAssessment: text("mutagenicity_consensus_assessment"),
	mutagenicityConsensusPrediction: text("mutagenicity_consensus_prediction"),
	mutagenicityCaesarAssessment: text("mutagenicity_caesar_assessment"),
	mutagenicityCaesarPrediction: text("mutagenicity_caesar_prediction"),
	mutagenicityIssAssessment: text("mutagenicity_iss_assessment"),
	mutagenicityIssPrediction: text("mutagenicity_iss_prediction"),
	mutagenicitySarpyIrfmnAssessment: text("mutagenicity_sarpy_irfmn_assessment"),
	mutagenicitySarpyIrfmnPrediction: text("mutagenicity_sarpy_irfmn_prediction"),
	mutagenicityKnnReadAcrossAssessment: text("mutagenicity_knn_read_across_assessment"),
	mutagenicityKnnReadAcrossPrediction: text("mutagenicity_knn_read_across_prediction"),
	mutagenicityAromaticAminesAssessment: text("mutagenicity_aromatic_amines_assessment"),
	mutagenicityAromaticAminesPrediction: text("mutagenicity_aromatic_amines_prediction"),
	developmentalToxicityAssessment: text("developmental_toxicity_assessment"),
	developmentalToxicityPrediction: text("developmental_toxicity_prediction"),
	developmentalReproductiveToxicityAssessment: text("developmental_reproductive_toxicity_assessment"),
	developmentalReproductiveToxicityPrediction: text("developmental_reproductive_toxicity_prediction"),
	carcinogenicityCaesarAssessment: text("carcinogenicity_caesar_assessment"),
	carcinogenicityCaesarPrediction: text("carcinogenicity_caesar_prediction"),
	carcinogenicityIssAssessment: text("carcinogenicity_iss_assessment"),
	carcinogenicityIssPrediction: text("carcinogenicity_iss_prediction"),
	carcinogenicityIsscanCgxAssessment: text("carcinogenicity_isscan_cgx_assessment"),
	carcinogenicityIsscanCgxPrediction: text("carcinogenicity_isscan_cgx_prediction"),
	carcinogenicityAntaresAssessment: text("carcinogenicity_antares_assessment"),
	carcinogenicityAntaresPrediction: text("carcinogenicity_antares_prediction"),
	carcinogenicityOralClassificationAssessment: text("carcinogenicity_oral_classification_assessment"),
	carcinogenicityOralClassificationPrediction: text("carcinogenicity_oral_classification_prediction"),
	carcinogenicityOralSlopeFactorAssessment: text("carcinogenicity_oral_slope_factor_assessment"),
	carcinogenicityOralSlopeFactorPrediction: text("carcinogenicity_oral_slope_factor_prediction"),
	carcinogenicityInhalationClassificationAssessment: text("carcinogenicity_inhalation_classification_assessment"),
	carcinogenicityInhalationClassificationPrediction: text("carcinogenicity_inhalation_classification_prediction"),
	carcinogenicityInhalationSlopeFactorAssessment: text("carcinogenicity_inhalation_slope_factor_assessment"),
	carcinogenicityInhalationSlopeFactorPrediction: text("carcinogenicity_inhalation_slope_factor_prediction"),
	carcinogenicityMaleRatAssessment: text("carcinogenicity_male_rat_assessment"),
	carcinogenicityMaleRatPrediction: text("carcinogenicity_male_rat_prediction"),
	carcinogenicityFemaleRatAssessment: text("carcinogenicity_female_rat_assessment"),
	carcinogenicityFemaleRatPrediction: text("carcinogenicity_female_rat_prediction"),
	acuteToxicityAssessment: text("acute_toxicity_assessment"),
	acuteToxicityPrediction: text("acute_toxicity_prediction"),
	hepatotoxicityAssessment: text("hepatotoxicity_assessment"),
	hepatotoxicityPrediction: text("hepatotoxicity_prediction"),
	logpMeylanKowwinAssessment: text("logp_meylan_kowwin_assessment"),
	logpMeylanKowwinPrediction: text("logp_meylan_kowwin_prediction"),
	logpMlogpAssessment: text("logp_mlogp_assessment"),
	logpMlogpPrediction: text("logp_mlogp_prediction"),
	logpAlogpAssessment: text("logp_alogp_assessment"),
	logpAlogpPrediction: text("logp_alogp_prediction"),
	organism: text(),
});

export const dntTripa = pgTable("dnt_tripa", {
	articleChemblId: varchar("article_chembl_id", { length: 50 }),
	compoundName: text("compound_name"),
	molecularWeight: text("molecular_weight"),
	molecularFormula: text("molecular_formula"),
	alogp: text(),
	smiles: text(),
	standardType: text("standard_type"),
	standardRelation: text("standard_relation"),
	standardValue: text("standard_value"),
	standardUnits: text("standard_units"),
	comment: text(),
	mutagenicityConsensusAssessment: text("mutagenicity_consensus_assessment"),
	mutagenicityConsensusPrediction: text("mutagenicity_consensus_prediction"),
	mutagenicityCaesarAssessment: text("mutagenicity_caesar_assessment"),
	mutagenicityCaesarPrediction: text("mutagenicity_caesar_prediction"),
	mutagenicityIssAssessment: text("mutagenicity_iss_assessment"),
	mutagenicityIssPrediction: text("mutagenicity_iss_prediction"),
	mutagenicitySarpyIrfmnAssessment: text("mutagenicity_sarpy_irfmn_assessment"),
	mutagenicitySarpyIrfmnPrediction: text("mutagenicity_sarpy_irfmn_prediction"),
	mutagenicityKnnAssessment: text("mutagenicity_knn_assessment"),
	mutagenicityKnnPrediction: text("mutagenicity_knn_prediction"),
	mutagenicityAromaticAminesAssessment: text("mutagenicity_aromatic_amines_assessment"),
	mutagenicityAromaticAminesPrediction: text("mutagenicity_aromatic_amines_prediction"),
	developmentalToxicityCaesarAssessment: text("developmental_toxicity_caesar_assessment"),
	developmentalToxicityCaesarPrediction: text("developmental_toxicity_caesar_prediction"),
	developmentalToxicityPgAssessment: text("developmental_toxicity_pg_assessment"),
	developmentalToxicityPgPrediction: text("developmental_toxicity_pg_prediction"),
	carcinogenicityCaesarAssessment: text("carcinogenicity_caesar_assessment"),
	carcinogenicityCaesarPrediction: text("carcinogenicity_caesar_prediction"),
	carcinogenicityIssAssessment: text("carcinogenicity_iss_assessment"),
	carcinogenicityIssPrediction: text("carcinogenicity_iss_prediction"),
	carcinogenicityIrfmnIsscanCgxAssessment: text("carcinogenicity_irfmn_isscan_cgx_assessment"),
	carcinogenicityIrfmnIsscanCgxPrediction: text("carcinogenicity_irfmn_isscan_cgx_prediction"),
	carcinogenicityIrfmnAntaresAssessment: text("carcinogenicity_irfmn_antares_assessment"),
	carcinogenicityIrfmnAntaresPrediction: text("carcinogenicity_irfmn_antares_prediction"),
	carcinogenicityOralClassAssessment: text("carcinogenicity_oral_class_assessment"),
	carcinogenicityOralClassPrediction: text("carcinogenicity_oral_class_prediction"),
	carcinogenicityOralSlopeAssessment: text("carcinogenicity_oral_slope_assessment"),
	carcinogenicityOralSlopePrediction: text("carcinogenicity_oral_slope_prediction"),
	carcinogenicityInhalationClassAssessment: text("carcinogenicity_inhalation_class_assessment"),
	carcinogenicityInhalationClassPrediction: text("carcinogenicity_inhalation_class_prediction"),
	carcinogenicityInhalationSlopeAssessment: text("carcinogenicity_inhalation_slope_assessment"),
	carcinogenicityInhalationSlopePrediction: text("carcinogenicity_inhalation_slope_prediction"),
	carcinogenicityMaleRatAssessment: text("carcinogenicity_male_rat_assessment"),
	carcinogenicityMaleRatPrediction: text("carcinogenicity_male_rat_prediction"),
	carcinogenicityFemaleRatAssessment: text("carcinogenicity_female_rat_assessment"),
	carcinogenicityFemaleRatPrediction: text("carcinogenicity_female_rat_prediction"),
	acuteToxicityAssessment: text("acute_toxicity_assessment"),
	acuteToxicityPrediction: text("acute_toxicity_prediction"),
	hepatotoxicityAssessment: text("hepatotoxicity_assessment"),
	hepatotoxicityPrediction: text("hepatotoxicity_prediction"),
	logpMeylanAssessment: text("logp_meylan_assessment"),
	logpMeylanPrediction: text("logp_meylan_prediction"),
	logpMlogpAssessment: text("logp_mlogp_assessment"),
	logpMlogpPrediction: text("logp_mlogp_prediction"),
	logpAlogpAssessment: text("logp_alogp_assessment"),
	logpAlogpPrediction: text("logp_alogp_prediction"),
});
