-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE IF NOT EXISTS "doenca_chagas" (
	"ChEMBL ID" text,
	"Name" text,
	"Synonyms" text,
	"Type" text,
	"Max Phase" double precision,
	"Molecular Weight" double precision,
	"Targets" double precision,
	"Bioactivities" double precision,
	"AlogP" text,
	"Polar Surface Area" text,
	"HBA" text,
	"HBD" text,
	"#RO5 Violations" text,
	"#Rotatable Bonds" text,
	"Passes Ro3" text,
	"QED Weighted" text,
	"CX Acidic pKa" text,
	"CX Basic pKa" text,
	"CX LogP" text,
	"CX LogD" text,
	"Aromatic Rings" text,
	"Structure Type" text,
	"Inorganic Flag" text,
	"Heavy Atoms" text,
	"HBA (Lipinski)" text,
	"HBD (Lipinski)" text,
	"#RO5 Violations (Lipinski)" text,
	"Molecular Weight (Monoisotopic)" double precision,
	"Np Likeness Score" text,
	"Molecular Species" text,
	"Molecular Formula" text,
	"Smiles" text,
	"Inchi Key" text,
	"Inchi" text,
	"Withdrawn Flag" text,
	"Orphan" bigint
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "doenca_leishmaniose" (
	"ChEMBL ID" text,
	"Name" text,
	"Synonyms" text,
	"Type" text,
	"Max Phase" double precision,
	"Molecular Weight" double precision,
	"Targets" double precision,
	"Bioactivities" double precision,
	"AlogP" text,
	"Polar Surface Area" text,
	"HBA" text,
	"HBD" text,
	"#RO5 Violations" text,
	"#Rotatable Bonds" text,
	"Passes Ro3" text,
	"QED Weighted" text,
	"CX Acidic pKa" text,
	"CX Basic pKa" text,
	"CX LogP" text,
	"CX LogD" text,
	"Aromatic Rings" text,
	"Structure Type" text,
	"Inorganic Flag" text,
	"Heavy Atoms" text,
	"HBA (Lipinski)" text,
	"HBD (Lipinski)" text,
	"#RO5 Violations (Lipinski)" text,
	"Molecular Weight (Monoisotopic)" double precision,
	"Np Likeness Score" text,
	"Molecular Species" text,
	"Molecular Formula" text,
	"Smiles" text,
	"Inchi Key" text,
	"Inchi" text,
	"Withdrawn Flag" text,
	"Orphan" bigint
);

*/